#!/usr/bin/env bash
SCORE=0
while read LINE
do
  echo [[$LINE]]
  POINTS=0
  MATCHES=()
  MATCH_COUNT=0
  while IFS='|' read A B
  do
    A=${A/*: /}
    NUMBERS=($B)
    for NUMBER in ${NUMBERS[@]}
    do
      if [[ "$A" =~ [[:space:]]$NUMBER[[:space:]] ]]
      then
        MATCHES+=($NUMBER)
        ((MATCH_COUNT++))
        if [[ $POINTS == 0 ]]
        then
          POINTS=1
        else
          ((POINTS=POINTS*2))
        fi
      fi
    done
    ((SCORE+=$POINTS))
    echo "$MATCH_COUNT matches (${MATCHES[@]}), Points are $POINTS, Score is $SCORE"
  done <<< $LINE
done < input