#!/bin/bash
declare -A v
n=()
e=()
s=()
w=()

line_num=0
while read line
do
    #echo -e "W\t$line_num\t$line" #from west to east
    w+=("$line")
    #echo -e "E\t$line_num\t$(echo $line | rev)" #from east to west
    e+=("$(echo $line | rev)")

    for (( col_num=0; col_num<=98; col_num++))
    do
        v[$col_num]="${v[$col_num]}${line:$col_num:1}"
    done

    ((line_num=$line_num+1))
done

for (( i=0; i<=98; i++ ))
do
    #echo -e "N\t$i\t${v[$i]}" #from north to south
    n+=("${v[$i]}")
    #echo -e "S\t$i\t$(echo ${v[$i]} | rev)" #from south to north
    s+=("$(echo ${v[$i]} | rev)")
done

for (( column=0; column<=98; column++ ))
do
    n_tallest=0; e_tallest=0; s_tallest=0; w_tallest=0;
    for (( position=0; position<=98; position++))
    do
        if [[ $n_tallest -lt ${n[$column]:$position:1} ]]
        then
            n_tallest=${n[$column]:$position:1}
            ((visible=$visible+1))
        fi
        if [[ $e_tallest -lt ${e[$column]:$position:1} ]]
        then
            e_tallest=${e[$column]:$position:1}
            ((visible=$visible+1))
        fi
        if [[ $s_tallest -lt ${s[$column]:$position:1} ]]
        then
            s_tallest=${s[$column]:$position:1}
            ((visible=$visible+1))
        fi
        if [[ $w_tallest -lt ${w[$column]:$position:1} ]]
        then
            w_tallest=${w[$column]:$position:1}
            ((visible=$visible+1))
        fi
    done
done

echo "Total visible: $visible"